language: cpp

branches:
  only:
    - master

matrix:
  include:
    # Works on Precise & Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - wget https://cmake.org/files/v3.13/cmake-3.13.3-Linux-x86_64.tar.gz -O /tmp/cmake.tgz
  - tar -zxvf /tmp/cmake.tgz
  - export PATH=$PWD/cmake-3.13.3-Linux-x86_64/bin:$PATH

script:
  - mkdir -p build && cd build && export PATH=$PATH:$PWD
  - cmake --version
  - cmake ..
  - make
  - make test
