name: Build and test

on:
  push:
    branches:
      -master

jobs:
  build-test:
    name: Build then unit test binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        cxx: [g++-9, clang-9]
    steps:
      - name: Install build tools
        run: |
          brew update
          brew install gcc@9 llvm@9 cmake
      - name: Clone repo
        uses: actions/checkout@v1
      - name: Compile then test
        run: |
          mkdir build
          cd build
          cmake -D CMAKE_CXX_COMPILER="$(which ${{ matrix.cxx }})" ..
          make
          make test

